version: '3.9'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-maria
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud_network
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_HOST
      - REDIS_HOST_PASSWORD
    depends_on:
      - db
      - redis

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass someredispassword
    restart: unless-stopped
    networks:
      - nextcloud_network
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app

volumes:
  db:
  nextcloud:
  nextcloud_data:

networks:
  nextcloud_network:

# docker-compose -f docker-compose-redis.yml up -d
# docker-compose -f docker-compose-redis.yml down -v